force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Recommendations</relationshipLabel>
    <relationshipName>Recommendations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Books4EveryoneHomeController.cls
/**
 * Books4EveryoneHomeController.cls
 * Controller used for Trailhead Books4Everyone UnmanagedPackage.
 * 
 * @authors: Trailhead, Jason (Trineo)
 * @date: February 2019
 */
public with sharing class Books4EveryoneHomeController {
    /**
     * Get a list of books and their description
     */
	@AuraEnabled
	public static List<Book__c> getBooks(){
    	return [
        	SELECT Id, Name, Description__c
        	FROM Book__c
    	];
    }

    /**
     * Get a list of books with their author and a description
     * of the book
     */
    @AuraEnabled
    public static List<Book__c> getBooksAndAuthor() {
        return [
            SELECT Id, Name, Description__c, Author__r.Name
            FROM Book__c
        ];
    }
    
    /**
     * Get a list of book recommendation values with book name and review. 
     */
    @AuraEnabled
    public static List<Recommendation__c> getBookRecommendations(){
    	return [
            SELECT Name, Review__c, Rating__c, Book__r.Name, Book__r.Author__r.Name
        	FROM Recommendation__c
        	WHERE Book__c != null
        ];
    }
    
    /**
     * Get a list of books that do not have authors listed in our
     * database
     */
    @AuraEnabled
    public static List<Book__c> getBooksWithoutAuthors(){
        return [
            SELECT Name
            FROM Book__c
            WHERE Author__c = null
        ];
    }
}