force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Pokémon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokémon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema.</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer_pokemon__c/Trainer_pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Trainer Pokémon</label>
    <nameField>
        <displayFormat>P{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainer Pokémon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer_pokemon__c/fields/Acquired__c.field-meta.xml
<CustomField>
    <fullName>Acquired__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Has the trainer acquired this pokémon</inlineHelpText>
    <label>Acquired?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokémon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <inlineHelpText>The trainer this pokémon belongs to</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PokemonTriggerHandler.cls
/**
 * Class: PokemonTriggerHandler.cls
 * Test: PokemonTriggerHandlerTest.cls
 */
public class PokemonTriggerHandler extends TriggerHandler{

    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}

    public override void afterInsert() {
        this.createNewTrainerPokemonLink(Trigger.new);
    }

    public override void afterUpdate() {}
    public override void afterDelete() {}
    public override void afterUndelete() {}

    /**
     * If a new Pokemon is created, make a new Trainer Pokemon record for every trainer
     * @param   List<Pokemon__c>. All new pokemon records
     */
    @TestVisible
    private void createNewTrainerPokemonLink(List<Pokemon__c> newPkmn) {
        List<Trainer_Pokemon__c> newLinkRecords = new List<Trainer_Pokemon__c>();
        List<Trainer__c> allTrainers = [SELECT Id FROM Trainer__c];

        for (Pokemon__c pkmn : newPkmn) {
            for (Trainer__c theTrainer : allTrainers) {
                Trainer_Pokemon__c newLink = new Trainer_Pokemon__c();
                newLink.Pokemon__c  = pkmn.Id;
                newLink.Trainer__c  = theTrainer.Id;
                newLink.Acquired__c = false;
                newLinkRecords.add(newLink);
            }
        }

        try {
            insert newLinkRecords;
            System.debug('New link records were successfully inserted.');
            System.debug(newLinkRecords);
        } catch (Exception e) {
            System.debug('Couldn\'t insert the new link records because');
            System.debug(e.getMessage());
        }
    }

}