force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Pokémon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokémon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema.</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer_pokemon__c/Trainer_pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Trainer Pokémon</label>
    <nameField>
        <displayFormat>P{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainer Pokémon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer_pokemon__c/fields/Acquired__c.field-meta.xml
<CustomField>
    <fullName>Acquired__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Has the trainer acquired this pokémon</inlineHelpText>
    <label>Acquired?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokémon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <inlineHelpText>The trainer this pokémon belongs to</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TrainerTriggerHandler.cls
/**
 * Class: TrainerTriggerHandler.cls
 * Test: TrainerTriggerHandlerTest.cls
 */
public class TrainerTriggerHandler extends TriggerHandler{

    // public override void beforeInsert() {}
    // public override void beforeUpdate() {}
    // public override void beforeDelete() {}

    public override void afterInsert() {
        this.initialSetupForTrainerRecord(Trigger.new);
    }

    // public override void afterUpdate() {}
    // public override void afterDelete() {}
    // public override void afterUndelete() {}

    /**
     * Has to be run after insert so the Trainer records have an Id. Sets up an record to link
     * each existing pokemon record to the trainer with a Trainer Pokemon record
     * @param   List<Trainer__c>. List of new trainers after they've been inserted
     */
    @TestVisible
    private void initialSetupForTrainerRecord(List<Trainer__c> newTrainers) {
        List<Trainer_Pokemon__c> newLinkRecords = new List<Trainer_Pokemon__c>();
        List<Pokemon__c> allPokemon = [SELECT Id FROM Pokemon__c];
        if (allPokemon.isEmpty()) { return; }

        for (Trainer__c theTrainer : newTrainers) {
            for (Pokemon__c pkm : allPokemon) {
                Trainer_Pokemon__c linkRecord = new Trainer_Pokemon__c();
                linkRecord.Trainer__c  = theTrainer.Id;
                linkRecord.Pokemon__c  = pkm.Id;
                linkRecord.Acquired__c = false;
                newLinkRecords.add(linkRecord);
            }
        }

        try {
            insert newLinkRecords;
            // System.debug('New records successfully inserted for new trainers:');
            // System.debug(newTrainers);
        } catch (Exception e) {
            System.debug('New records couldn\'t be inserted for new trainers');
            System.debug(e.getMessage());
        }
    }

}