force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Pokémon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokémon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <inlineHelpText>The region the pokémon is from.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pokemon_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Types__c.field-meta.xml
<CustomField>
    <fullName>Types__c</fullName>
    <label>Type(s)</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pokemon_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema.</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer__c/fields/Game_Version__c.field-meta.xml
<CustomField>
    <fullName>Game_Version__c</fullName>
    <label>Game Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shield</fullName>
            </value>
            <value>
                <fullName>Sword</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainer__c/fields/Total_Available_Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Total_Available_Pokemon__c</fullName>
    <inlineHelpText>Total amount of pokémon currently available.</inlineHelpText>
    <label>Total Available Pokémon</label>
    <summaryForeignKey>Trainer_pokemon__c.Trainer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trainer__c/fields/Total_Unique_Caught__c.field-meta.xml
<CustomField>
    <fullName>Total_Unique_Caught__c</fullName>
    <inlineHelpText>How many unique pokémon have been caught.</inlineHelpText>
    <label>Total Unique Caught</label>
    <summaryFilterItems>
        <field>Trainer_pokemon__c.Acquired__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Trainer_pokemon__c.Trainer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/Trainer_pokemon__c.object-meta.xml
<CustomObject>
    <description>Used in pokemon schema</description>
    <label>Trainer Pokémon</label>
    <nameField>
        <displayFormat>P{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainer Pokémon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer_pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokémon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainer_pokemon__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <inlineHelpText>The trainer this pokémon belongs to</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainer Pokémon</relationshipLabel>
    <relationshipName>Trainer_Pokemon</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Pokemon_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Original</fullName>
    </customValue>
    <customValue>
        <fullName>Alola</fullName>
    </customValue>
    <customValue>
        <fullName>Galar</fullName>
    </customValue>
    <description>The region a pokémon is from</description>
    <masterLabel>Pokémon Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pokemon_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>The different types a pokémon can be.</description>
    <masterLabel>Pokémon Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrainerTriggerHandlerTest.cls
/**
 * Class: TrainerTriggerHandlerTest.cls
 * Test for: TrainerTriggerHandler.cls
 */
@isTest
private class TrainerTriggerHandlerTest {

    private static final Integer P_MINIMUM = 5;
    private static final Integer P_OFFSET  = 15;
    private static final SObjectUtil UTIL_PKMN        = new SObjectUtil('Pokemon__c');
    private static final SObjectUtil UTIL_TRNR        = new SObjectUtil('Trainer__c');
    private static final List<String> P_GENDERS       = new List<String>{'None', 'Male; Female'};
    private static final List<String> P_TYPES         = TrainerTriggerHandlerTest.getAvailableTypes();
    private static final List<String> P_REGIONS       = TrainerTriggerHandlerTest.getAvailableRegions();
    private static final List<String> T_GAME_VERSIONS = TrainerTriggerHandlerTest.getAvailableVersions();

    /**
     * Insert a new trainer while no pokemon and no trainers
     */
    @isTest
    static void testOne() {
        //  Test initial record counts
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));

        Test.startTest();
        //  Create and insert test trainer record
        String trainerName = 'Ash Ketchup';
        Trainer__c testTrainer = TestObjectFactory.createSingleTestTrainer(trainerName, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Query trainer record
        Trainer__c queryTrainer = [
            SELECT Id, Name, Game_Version__c, Total_Unique_Caught__c, Total_Available_Pokemon__c
            FROM Trainer__c
            WHERE Id = :testTrainer.Id
        ];
        Test.stopTest();

        //  Test final record counts
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(1, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));
        System.assertNotEquals(null, queryTrainer.Id);
        System.assertEquals(trainerName, queryTrainer.Name);
        System.assert(T_GAME_VERSIONS.contains(queryTrainer.Game_Version__c));
        System.assertEquals(0, queryTrainer.Total_Unique_Caught__c);
        System.assertEquals(0, queryTrainer.Total_Available_Pokemon__c);
    }

    /**
     * Insert a new trainer while no pokemon, but existing trainers
     */
    @isTest
    static void testTwo() {
        //  Existing trainer
        String trainerName1 = 'Ash Ketchup';
        Trainer__c testTrainer1 = TestObjectFactory.createSingleTestTrainer(trainerName1, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Test initial record counts
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(1, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));

        Test.startTest();
        //  Create and insert test trainer record
        String trainerName2 = 'Gravy Oats';
        Trainer__c testTrainer2 = TestObjectFactory.createSingleTestTrainer(trainerName2, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Query trainer record
        Trainer__c queryTrainer = [
            SELECT Id, Name, Game_Version__c, Total_Unique_Caught__c, Total_Available_Pokemon__c
            FROM Trainer__c
            WHERE Id = :testTrainer2.Id
        ];
        Test.stopTest();

        //  Test final record counts
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(2, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));
        System.assertNotEquals(null, queryTrainer.Id);
        System.assertEquals(trainerName2, queryTrainer.Name);
        System.assert(T_GAME_VERSIONS.contains(queryTrainer.Game_Version__c));
        System.assertEquals(0, queryTrainer.Total_Unique_Caught__c);
        System.assertEquals(0, queryTrainer.Total_Available_Pokemon__c);
    }

    /**
     * Insert a new trainer with existing pokemon, but no trainers
     */
    @isTest
    static void testThree() {
        List<Pokemon__c> testPokemon = TrainerTriggerHandlerTest.createTestPokemonRecords();
        //  Test initial record counts
        System.assertEquals(testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(0, TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));

        Test.startTest();
        //  Create and insert test trainer record
        String trainerName = 'Gravy Oats';
        Trainer__c testTrainer = TestObjectFactory.createSingleTestTrainer(trainerName, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Query trainer record
        Trainer__c queryTrainer = [
            SELECT Id, Name, Game_Version__c, Total_Unique_Caught__c, Total_Available_Pokemon__c
            FROM Trainer__c
            WHERE Id = :testTrainer.Id
        ];
        Test.stopTest();

        //  Test final record counts
        System.assertEquals(testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(1, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(1 * testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));
        System.assertNotEquals(null, queryTrainer.Id);
        System.assertEquals(trainerName, queryTrainer.Name);
        System.assert(T_GAME_VERSIONS.contains(queryTrainer.Game_Version__c));
        System.assertEquals(0, queryTrainer.Total_Unique_Caught__c);
        System.assertEquals(testPokemon.size(), queryTrainer.Total_Available_Pokemon__c);
    }

    /**
     * Insert a new trainer with existing pokemon and trainers
     */
    @isTest
    static void testFour() {
        //  Existing trainer
        String trainerName1 = 'Ash Ketchup';
        Trainer__c testTrainer1 = TestObjectFactory.createSingleTestTrainer(trainerName1, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Existing pokemon
        List<Pokemon__c> testPokemon = TrainerTriggerHandlerTest.createTestPokemonRecords();
        //  Test initial record counts
        System.assertEquals(testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(1, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(1 * testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));

        Test.startTest();
        //  Create and insert test trainer record
        String trainerName2 = 'Gravy Oats';
        Trainer__c testTrainer2 = TestObjectFactory.createSingleTestTrainer(trainerName2, T_GAME_VERSIONS.get( Integer.valueof(Math.random() * T_GAME_VERSIONS.size()) ), true);
        //  Query trainer record
        Trainer__c queryTrainer = [
            SELECT Id, Name, Game_Version__c, Total_Unique_Caught__c, Total_Available_Pokemon__c
            FROM Trainer__c
            WHERE Id = :testTrainer2.Id
        ];
        Test.stopTest();

        //  Test final record counts
        System.assertEquals(testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Pokemon__c'));
        System.assertEquals(2, TestObjectFactory.getSObjectRecordCount('Trainer__c'));
        System.assertEquals(2 * testPokemon.size(), TestObjectFactory.getSObjectRecordCount('Trainer_Pokemon__c'));
        System.assertNotEquals(null, queryTrainer.Id);
        System.assertEquals(trainerName2, queryTrainer.Name);
        System.assert(T_GAME_VERSIONS.contains(queryTrainer.Game_Version__c));
        System.assertEquals(0, queryTrainer.Total_Unique_Caught__c);
        System.assertEquals(testPokemon.size(), queryTrainer.Total_Available_Pokemon__c);
    }

    /* Private functions specific for this unit test class */

    /**
     * Returns a list of available know pokemon types
     * @return  List<String>
     */
    private static List<String> getAvailableTypes() {
        List<String> newTypes = new List<String>();
        for (Schema.PicklistEntry ple : UTIL_PKMN.mapPicklistValues.get('Types__c')) {
            newTypes.add(ple.Label);
        }
        return newTypes;
    }

    /**
     * Returns a list of available known pokemon regions
     * @return  List<String>
     */
    private static List<String> getAvailableRegions() {
        List<String> newRegions = new List<String>();
        for (Schema.PicklistEntry ple : UTIL_PKMN.mapPicklistValues.get('Region__c')) {
            newRegions.add(ple.Label);
        }
        return newRegions;
    }

    /**
     * Returns a list of available known game versions
     * @return  List<String>
     */
    private static List<String> getAvailableVersions() {
        List<String> newVersions = new List<String>();
        for (Schema.PicklistEntry ple : UTIL_TRNR.mapPicklistValues.get('Game_Version__c')) {
            newVersions.add(ple.Label);
        }
        return newVersions;
    }

    /**
     * Creates a random amount of test pokemon records
     * @return  List<Pokemon__c>
     */
    private static List<Pokemon__c> createTestPokemonRecords() {
        Integer numberOfPokemon = Integer.valueOf(Math.random() * P_OFFSET) + P_MINIMUM;
        List<Pokemon__c> testPokemon = new List<Pokemon__c>();
        for (Integer pCount = 0; pCount < numberOfPokemon; pCount++) {
            //  Its name
            String pTestName = 'Test pMon #' + String.valueOf(pCount+1);

            //  Its type(s): Randomly assign 1-2 types from the list of known types
            String pTestTypes = '';
            Integer numberOfTypes = Integer.valueOf(Math.random() * 2) + 1;
            for  (Integer tCount = 1; tCount <= numberOfTypes; tCount++) {
                pTestTypes += P_TYPES.get( Integer.valueof(Math.random() * P_TYPES.size()) );
                if (tCount < numberOfTypes) {
                    pTestTypes += '; ';
                }
            }

            //  Its available genders
            String pTestGender = '';
            pTestGender += P_GENDERS.get( Integer.valueof(Math.random() * P_GENDERS.size()) );

            //  Create and add to list of test pokemon
            testPokemon.add(TestObjectFactory.createSingleTestPokemon(pCount + 1, pTestName, pTestTypes, pTestGender, '', false));
        }
        try {
            insert testPokemon;
            System.debug('Test pokemon records inserted');
        } catch (Exception e) {
            System.debug('Test pokemon records not inserted:');
            System.debug(e.getMessage());
        }

        Integer pokemonRecordCount = [SELECT Count() FROM Pokemon__c];
        System.assertEquals(numberOfPokemon, pokemonRecordCount, 'The number of records inserted does not match what was expected.');

        return testPokemon;
    }
}